### ISSUE TITLE
💾 Questionnaire

### ISSUE THREAD

**Issue by garydevenay** [garydevenay/operationcovid19#1]
**As a User I would like the ability to log my information and symptoms so that I can contribute to tracking the virus spread.**

## Questionnaire

1. Where are you located?
2. Have you been in contact with someone who tested positive for COVID-19 in the last 30 days?
3. Have you been tested positive for COVID-19?
4. Where did you get tested?
4.1.0. Have you since been cleared of COVID-19?
4.1.1. When were you cleared?
5. Are you currently self isolating?
6. Do you have any of the following symptoms?
6.1. A fever above 37.8°C (100°F)
6.2. Persistent cough
6.3. Tiredness
6.4. Aches and pains,
6.5. Nasal congestion,
6.6. Runny nose, 
6.7. Sore throat,
6.8. Diarrhea
6.9. Other - Free-text
7. Are you over 65 years of age?
8. Do you have a pre-existing condition?
8.1. FREE-TEXT RESPONSE: Enter medical condition
9. Voluntary Information 
9.1. FREE-TEXT RESPONSE: First Name, Last Name, Age, City of residency, travel in the last 90 days, have you been to any public gatherings over 100 people in the last 30 days?

**Comment by garydevenay** [comment]
This is just about ready to go. The only remaining tasks to be completed are:

1. Pull together question answers to a unified JSON object.
2. Take a once over on validation
3. Mark required fields clearly
4. Tie it up to the output of Issue #6

**Comment by jkowalchuk** [comment]
Agu (Linkedin)
There were two important omissions: recent COVID-19 recovery and reinfection information. I'd add a question each about whether the respondent has recently recovered and/or been reinfected.

In addition, there are a few minor grammatical things to consider. If you compare my corrections with the original text, you'll see what I mean. Please find them attached below:

3. Have you tested positive for COVID-19?

5. Are you currently self-isolating?

6.4. Aches and pains
6.5. Nasal congestion
6.6. Runny nose
6.7. Sore throat
6.9. Other: Free-text response

8.1. Free-text Response: Enter medical condition (if any)

9.1. Free-text Response: 
First Name, Middle Initial (if any), Last Name:
Age: 
City of residence:
Travel in the last 90 days: 
Have you been to any public gatherings with* over 100 people in the last 30 days? Yes or No
If yes, where and when? Please provide information on all instances.  (edited)

Other than the grammatical and punctuation corrections, I don't think that 9.1 should be labelled voluntary or mandatory. It should just be a part of the questionnaire. That'll encourage people who agree to participate to answer the question. 

Making it voluntary is somewhat redundant because the respondent has already volunteered to do the survey, and it might have the unintended consequence of people skipping it altogether. That defeats the purpose of doing the survey anyway. The information is important.

Middle initials and middle names are important too, because there are so many identical first and last names out there. The middle initial helps narrow them down a bit.

Giving each piece of information in 9.1 its own field helps reduce clutter.

**Comment by jkowalchuk** [comment]
1. Where are you located?
2. Have you been in contact with someone who tested positive for COVID-19 in the last 30 days?

3. Have you tested positive for COVID-19?

4. Where did you get tested?
4.1.0. Have you since been cleared of COVID-19?
4.1.1. When were you cleared?

5. Are you currently self-isolating?
6. Do you have any of the following symptoms?
6.1. A fever above 37.8°C (100°F)
6.2. A persistent cough (coughing a lot for more than an hour, or 3 or more coughing episodes in 24 hours)
6.3. Fatigue/tiredness
6.4. Body aches and pains
6.5. Nasal congestion
6.6. Runny nose
6.7. Sore throat
6.8. Diarrhea
6.9 Abdominal pain
6.10. Shortness of breath
6.11. Loss of smell/taste
6.12. Hoarse Voice
6.13. Chest pain /tightness in your chest
6.14. Disorientation, confusion or drowsiness
6.15. Other Free-text

8.1. Free-text Response: Enter medical condition (if any)

9.1. Free-text Response:
First Name, Middle Initial (if any), Last Name:
Age:
City of residence:
Travel in the last 90 days:
Have you been to any public gatherings with* over 100 people in the last 30 days? Yes or No
If yes, where and when? Please provide information on all instances. (edited)

**Comment by jkowalchuk** [comment]
Includes: 

https://cov-clear.com/survey/
https://covid.joinzoe.com
https://111.nhs.uk/Question/Navigation
